[project]
name = "qldpc"
dependencies = [
"galois",
"pandas",
"numpy",
"scipy",
"matplotlib",
"pypdf2",
"pytest",
"networkx<3.0.0",
]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
