[project]
name = "qldpc"
dependencies = [
"galois=0.0.31",
"pandas>=1.4",
"numpy>=1.22",
"scipy>=1.8",
"matplotlib>=3.0",
"pytest>=7.0",
"networkx>=2.8,<3.0",
]

[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"
