name: starter-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v17
      - name: Build nix derivation and run pytest
        run: | 
          nix --extra-experimental-features "nix-command flakes" run . -- -m pytest
